<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>BTDeviceBatteryInfo</RootNamespace>
    <AssemblyName>BTDeviceBatteryInfo</AssemblyName>
    <Product>BT Device Battery Info</Product>
    <Description>Widget para consultar el estado y la batería de dispositivos Bluetooth en Windows.</Description>
    <Copyright>Boris SdK</Copyright>
    <Version>0.21</Version>
    <ApplicationIcon>Assets/Icons/Icon-dark.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets/Icons/Icon-dark.ico" />
    <Resource Include="Assets/Icons/icon-dark-128.png" />
    <Resource Include="Assets/Icons/Icon-light.ico" />
    <Resource Include="Assets/Icons/icon-light-128.png" />
    <Resource Include="Assets/Fonts/GeistSans.ttf" />
    <Content Include="Assets/Licenses/Lucide-LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Assets/Fonts/Geist-OFL.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
